---
- hosts: all
  tasks:
    - name: add apt key for nodesource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      become: yes

    - name: add repo for nodesource
      apt_repository:
        repo: deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main
        # codename: xenial
        update_cache: yes
      become: yes

    - name: install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes

    - name: copy bashrc
      copy:
        src: ./files/.bashrc
        dest: ~/.bashrc
